name: field_form
description: Perform location-bound measurements in the field

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.9+21

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.10.1 # or the latest version on Pub
  google_maps_flutter_ios: 2.13.1
  json_serializable: ^6.0.0
  flutter_settings_ui: ^3.0.0
  path_provider: ^2.0.1
  share_plus: ^9.0.0
  file_picker: ^8.0.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.5
  intl: ^0.19.0
  sqflite:
  path:
  ftpconnect: ^2.0.7
  csv: ^6.0.0
  permission_handler: ^11.3.0
  http: ^1.2.1
#  cronet_http: ^1.3.1
#  cupertino_http: ^1.5.0
  flutter_localization: ^0.2.0
  camera:
  native_exif: ^0.6.0
  pure_ftp: ^0.7.5
  dartssh2: ^2.4.1
  flutter_datetime_picker_plus: ^2.0.1
  pdfx: ^2.3.0
  flutter_easy_search_bar: ^0.0.2
  map_launcher: ^3.1.0
  flutter_archive: ^6.0.0
  flutter_secure_storage: ^9.2.1
  geolocator: ^12.0.0
  # check_vpn_connection: ^0.0.2
  # webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Add the following two lines
  lints: ^4.0.0
  build_runner: ^2.1.4
  flutter_launcher_icons: ^0.13.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true
